### ISSUE TITLE
Update templates for AtoM 2.4

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ansible-atom#10]
gearman.yml, settings.yml, etc... see #14.

**Comment by djjuhasz** [comment]
I'm getting an error:

> To use the "removePattern" method, you must set the "storeCacheInfo" option to "true".

Which I think is related to https://projects.artefactual.com/issues/9671 and a change to the way memcache paramaters are defined in the apps/qubit/config/app.yml template.
