### ISSUE TITLE
Problem: Role fails when using python3

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/ansible-atom#47]
When using python 3 role fails with:

```
TASK [external-roles/artefactual-atom : Install pool configuration file ( Ubuntu >= 16.04 )] **********************************************************************************************************************
fatal: [XXXX.accesstomemory.org]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}
```

**Comment by mamedin** [comment]
It is related to the use of iteritems() on templates. For instance:

https://github.com/artefactual-labs/ansible-atom/blob/master/templates/etc/profile.d/atom.sh.j2#L4

Using items() instead of iteritems() on templates fixes the issue and works on python2 and python3.

It was applied to AM role here: https://github.com/artefactual-labs/ansible-archivematica-src/pull/197/files

**Comment by hakamine** [comment]
This problem has been addressed as one of the fixes proposed in this PR: https://github.com/artefactual-labs/ansible-atom/pull/46

**Comment by mamedin** [comment]
Thanks @hakamine!

**Comment by hakamine** [comment]
Closing this issue as #46 has been merged
