### ISSUE TITLE
atom_auto_init?

### ISSUE THREAD

**Issue by edsu** [artefactual-labs/ansible-atom#95]
What is the preferred way to deploy AtoM when not using `atom_auto_init`? I'm getting this error when I run [my playbook](https://github.com/umd-mith/mith-atom/blob/main/atom.yml):

```
TASK [artefactual.atom : Enable AtoM plug-ins] *****************************************************
failed: [ec2-34-207-123-168.compute-1.amazonaws.com] (item=qtSwordPlugin) => {"ansible_loop_var": "item", "changed": true, "cmd": "php symfony tools:atom-plugins add qtSwordPlugin", "delta": "0:00:00.081982", "end": "2021-05-18 23:01:54.408456", "item": "qtSwordPlugin", "msg": "non-zero return code", "rc": 1, "start": "2021-05-18 23:01:54.326474", "stderr": "\n                                                                                                      \n   [wrapped: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'atom.setting' doesn't exist]  \n                                                                                                      ", "stderr_lines": ["", "                                                                                                      ", "   [wrapped: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'atom.setting' doesn't exist]  ", "                                                                                                      "], "stdout": "", "stdout_lines": []}
```

I can confirm that my MySQL database has been created and is accessible, but lacks a schema.

**Comment by edsu** [comment]
I figured that I could pass this option once on the initial setup and leave it out of the playbook?

        ansible-playbook atom.yml --extra-vars "atom_auto_init=yes"

Is that what people usually do?

**Comment by sevein** [comment]
Thank you! It's still considered an experimental variable but the proposition is to leave `atom_auto_init=yes` set so you don't have to think again about the current state of your deployment, i.e. freshly installed vs already initialized. Long term we are considering making this the default, but we only make available behind a feature toggle until we hear more feedback.

Responding to your question, the usual practice is to set `atom_flush_data=yes` during your first deployment. This is probably the safest way at this point if you don't have time to experiment with `atom_auto_init=yes`.

**Comment by edsu** [comment]
Thanks for the quick feedback! I think it could be useful to put this information in the docs since using the role as is does not work.

**Comment by sevein** [comment]
We can try to clarify here: [Automatic database initialization](https://github.com/artefactual-labs/ansible-atom#automatic-database-initialization) needs to be clarified or were you using some other document? In any case, yes I think that's a good idea. We'll make it clearer!

**Comment by edsu** [comment]
Yes that is what I was looking at. I didn't make it part of my playback because I read that as a discouraged practice. Without that option the role doesn't seem to notice the database lacks a schema, which causes an error.
